In [2]:
# !pip install numpy

In [3]:
# Import NumPy Library

import numpy

In [4]:
# Example 1.1

import numpy

myArr = numpy.array([0, 1, 2, 3, 4, 5])
print(myArr)

[0 1 2 3 4 5]


In [5]:
# Alias of NumPy Library

import numpy as np

In [6]:
# Example 1.2

import numpy as np

myArr = np.array([0, 1, 2, 3, 4, 5])
print(myArr)

[0 1 2 3 4 5]


In [7]:
# NumPy Array
# myArray = np.array([v1, v2, v3,...]) # the first syntax
# myArray = np.arange( v1, v2 ) # the second syntax

In [8]:
# Example 1.3

import numpy as np

arr1 = np.array([0, 1, 2, 3, 4, 5])
print(arr1)

arr2 = np.arange( 0, 6 ) # not include 6
print(arr2)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [9]:
# Zero-Dimensional Array

# myArray = np.array(value)

In [10]:
# Example 1.4

import numpy as np

myArray = np.array(100)
print(myArray)

100


In [11]:
# One-Dimensional Array

# myArray = np.array([value1, value2, value3……])

In [12]:
# Example 1.5

import numpy as np

myArray = np.array([0, 1, 2, 3, 4, 5])
print(myArray)

[0 1 2 3 4 5]


In [13]:
# Two-Dimensional Array

# myArray = np.array( [ [v1, v2, v3] , [v4, v5, v6] ] )

In [14]:
# Example 1.6

import numpy as np

myArray = np.array([[0, 1, 2], [3, 4, 5]])
print(myArray)

[[0 1 2]
 [3 4 5]]


In [15]:
# Three-Dimensional Array

# myArr = np.array( [[[v1, v2, v3] , [v4, v5, v6], [v7, v8, v9]]] )

In [16]:
# Example 1.7

import numpy as np

myArr = np.array([[[0,1,2], [3,4,5], [6,7,8]]])
print(myArr)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [17]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
numpy: 1.23.0



### End.