In [1]:
# High Dimension Array

# ndmin = number

In [2]:
# Example 2.1

import numpy as np

arr3 = np.array([ 0, 1, 2, 3 ], ndmin=3) # define 3d array
arr4 = np.array([ 0, 1, 2, 3 ], ndmin=4) # define 4d array
arr5 = np.array([ 0, 1, 2, 3 ], ndmin=5) # define 5d array
print(arr3)
print(arr4)
print(arr5)

[[[0 1 2 3]]]
[[[[0 1 2 3]]]]
[[[[[0 1 2 3]]]]]


In [3]:
# The Number of Dimension

# myArray.ndim

In [4]:
# Example 2.2

import numpy as np

arr0 = np.array(100) # 0d array
arr1 = np.array([0, 1, 2, 3, 4, 5]) # 1d array
arr2 = np.array([[0, 1, 2], [3, 4, 5,]]) # 2d array
arr3 = np.array([[[0,1,2], [3,4,5], [6,7,8]]]) # 3d array
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [5]:
# Access the Array Element

# myArray[index]

In [6]:
# Example 2.3

import numpy as np

myArray = np.array([10, 11, 12, 13, 14])

print(myArray[0])
print(myArray[3])

10
13


In [7]:
# Calculate the Element Values

In [8]:
# Example 2.4

import numpy as np

myArray = np.array([10, 11, 12, 13, 14])

print(myArray[0] + myArray[3])
print(myArray[1] * myArray[2])

23
132


In [9]:
# Access Two-Dimensional Array

# myArray[ row, col ]

In [10]:
# Example 2.5

import numpy as np

arr = np.array([[10,11,12,13,14], [15,16,17,18,19]])

print ('The value in row 0 and col 3 is: ', arr[0,3])
print ('The value in row 1 and col 2 is: ', arr[1,2])

The value in row 0 and col 3 is:  13
The value in row 1 and col 2 is:  17


In [11]:
# Last Index

# myArray[-1, -1] # access the last row and the last col

In [12]:
# Example 2.6

import numpy as np

arr = np.array([[10,11,12,13,14], [15,16,17,18,19]])

print ('The value in row 0 and the last col is: ', arr[0,-1])
print ('The value in the last row and col 2 is: ', arr[-1,2])
print ('The value in the last row & the last col is: ', arr[-1,-1])

The value in row 0 and the last col is:  14
The value in the last row and col 2 is:  17
The value in the last row & the last col is:  19


In [13]:
# NumPy Slicing

# [ start : end : step ]

In [14]:
# Example 2.7

import numpy as np

arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])

print(arr[ 2:7:2 ])
print(arr[ 2:7 ])

[12 14 16]
[12 13 14 15 16]


In [15]:
# Slicing by Default

#The default value of “start” is the first index.
#The default value of “end” is the last index.
#The default value of “step” is 1

In [16]:
# Example 2.8

import numpy as np

arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])

print(arr[ :5])
print(arr[5: ])

[10 11 12 13 14]
[15 16 17 18]


In [17]:
# Negative Slicing

# arr[ -index1: -index2 ]

In [18]:
# Example 2.9

import numpy as np

arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])

print(arr[-5 : -2])
print(arr[-7 : -3])

[14 15 16]
[12 13 14 15]


In [19]:
# 2-D Array Slicing (1)

# myArray[row1: row2, col1: col2]

In [20]:
# Example 2.10

import numpy as np

arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])

print(arr[0:2, 2:4])

[[12 13]
 [17 18]]


In [21]:
# 2-D Array Slicing (2)

# myArray[row, col1:col2]

In [22]:
# Example 2.11

import numpy as np

arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])

print(arr[0, 1:4])
print(arr[1, 2:4])

[11 12 13]
[17 18]


In [23]:
# 2-D Array Slicing (3)

# myArray[row1: row2, col]

In [24]:
# Example 2.12

import numpy as np

arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])

print(arr[0:2, 2])
print(arr[0:1, 3])

[12 17]
[13]


In [25]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.