### NumPy Data Type

NumPy data type can be described by one character.

|Character | Data Type|
|--|--|
|i |integer or int64|
|b |boolean|
|u |unsigned|
|f |float|
|c |complex|
|m |timedelta|
|> |more than characters (bit-endian byte order)|
|< |less than characters (little-endian byte order)|
|M |datetime|
|O |object|
|S |string|
|U |unidcode|
|V | void|

In [1]:
# Check Data Type

# myArray.dtype

In [2]:
# Example 3.1

import numpy as np

arr1 = np.array([10, 11, 12, 13])
print(arr1.dtype)

arr2 = np.array(['Matlab','in', '8', 'Hours'])
print(arr2.dtype)

int32
<U6


In [3]:
# Set String Array

# dtype = ‘datatype’

In [4]:
# Example 3.2

import numpy as np

myArr = np.array([10, 20, 30, 40], dtype='S')
print(myArr.dtype)

|S2


In [5]:
# Set Int Array

# dtype = ‘datatype’

In [6]:
# Example 3.3

import numpy as np

myArr = np.array([10, 11, 12, 13], dtype='i2')
print(myArr.dtype)

int16


In [7]:
# Convert Integer Type

# myArr.astype(‘data_type’)

In [8]:
# Example 3.4

import numpy as np

myArr = np.array([0.99, 1.99, 2.99, 3.99])
arr = myArr.astype('i')

print(arr)
print(arr.dtype)

[0 1 2 3]
int32


In [9]:
# Convert Bool Type

# myArr.astype(‘data_type’)

In [10]:
# Example 3.5

import numpy as np

myArr = np.array([0, 1, 2, 3])
arr = myArr.astype(bool)

print(arr)
print(arr.dtype)

[False  True  True  True]
bool


In [11]:
# Copy an Array

# array2 = array1.copy()

In [12]:
# Example 3.6

import numpy as np

arr1 = np.array([0, 1, 2, 3, 4]) # arr1 is an original array
arr2 = arr1.copy() # arr2 is a new array
arr2[0] = 100

print(arr1)
print(arr2)

[0 1 2 3 4]
[100   1   2   3   4]


In [13]:
# The View of Array

# array2 = array1.view()

In [14]:
# Example 3.7

import numpy as np

arr1 = np.array([0, 1, 2, 3, 4]) # arr1 is an original array
arr2 = arr1.view() # arr2 is a view
arr2[0] = 100

print(arr1)
print(arr2)

[100   1   2   3   4]
[100   1   2   3   4]


In [15]:
# Check Correlation

In [16]:
# Example 3.8

import numpy as np

myArr = np.array([0, 1, 2, 3, 4])
copyArr = myArr.copy()
viewArr = myArr.view()

print(copyArr.base)
print(viewArr.base)

None
[0 1 2 3 4]


In [17]:
# Array Shape (1)

# array.shape

In [18]:
# Example 3.9

import numpy as np

myArr = np.array([[0,1,2,3],[4,5,6,7],[2,4,6,8]])
print(myArr.shape)

(3, 4)


In [19]:
# Array Shape (2)

In [20]:
# Example 3.10

import numpy as np

myArr = np.array([1, 2, 3, 4, 5], ndmin=2)

print(myArr)
print('The array shape is:', myArr.shape)

[[1 2 3 4 5]]
The array shape is: (1, 5)


In [21]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.