In [1]:
# Reshape From 1D to 2D

# 2dArray = 1dArray.reshape(rows, columns)

In [2]:
# Example 4.1

import numpy as np

myArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
newArr = myArr.reshape(3, 4)

print(newArr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
# Reshape From 2D to 3D

# 3dArray = 1dArray.reshape( layers, rows, columns )

In [4]:
# Example 4.2

import numpy as np

myArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
newArr = myArr.reshape(2, 2, 3)

print(newArr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
# Reshape Requirement

In [6]:
# Example 4.3

# arr.reshape( 2, 6 ) # 2*6=12
# arr.reshape( 3, 4 ) # 3*4=12
# arr.reshape( 4, 3 ) # 4*3=12

# arr.reshape( 1, 3, 4 ) # 1*3*4=12
# arr.reshape( 2, 3, 2 ) # 2*3*2=12
# arr.reshape( 3, 2, 2 ) # 3*2*2=12

In [7]:
# Unknown Dimension

# arr.reshape( -1, rows, columns )
# arr.reshape( layer, -1, columns )
# arr.reshape( layer, rows, -1 )

In [8]:
# Example 4.4

import numpy as np

myArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newArr = myArr.reshape( -1, 2, 3 )

print(newArr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
# Flattening Array

# myArr.reshape(-1)

In [10]:
# Example 4.5

import numpy as np

myArr = np.array([[1,2,3], [4,5,6], [7,8,9]])
newArr = myArr.reshape(-1)

print(newArr)

[1 2 3 4 5 6 7 8 9]


In [11]:
# Iterating 1-d Array

# for num in myArray

In [12]:
# Example 4.6

import numpy as np

myArr = np.array([10, 11, 12])

for num in myArr:
    print(num)

10
11
12


In [13]:
# Iterating 2-d Array

# for num in myArray

In [14]:
# Example 4.7

import numpy as np

myArr = np.array([[10, 11, 12], [13, 14, 15]])

for num in myArr:
    print(num)

[10 11 12]
[13 14 15]


In [15]:
# Iterating 3-d Array

# for num in myArray

In [16]:
# Example 4.8

import numpy as np

myArr=np.array([[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])

for num in myArr:
    print(num)

[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]


In [17]:
# nditer()

# nditer(myArray)

In [18]:
# Example 4.9

import numpy as np

myArr = np.array([[10, 11, 12], [13, 14, 15]])

for num in np.nditer(myArr): # myArr is a 2d array
    print(num)

10
11
12
13
14
15


In [19]:
# Example 4.10

import numpy as np

myArr=np.array([[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])

for num in np.nditer(myArr): # myArr is a 3d array
    print(num)

10
11
12
13
14
15
16
17
18
19
20
21


In [20]:
# Iterating with Step Length

# nditer( myArr[ :,: :step ] )

In [21]:
# Example 4.11

import numpy as np

myArr = np.array([[10, 11, 12, 13], [14, 15, 16, 17]])

for num in np.nditer(myArr[:,: :2]):
    print(num)

10
12
14
16


In [22]:
# Enumerating the Array

# ndenumerate(myArray)

In [23]:
# Example 4.12

import numpy as np

myArr = np.array([0, 1, 2, 3])

for id, num in np.ndenumerate(myArr):
    print(id, num)

(0,) 0
(1,) 1
(2,) 2
(3,) 3


In [24]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
numpy: 1.23.0



### End.