In [1]:
# Concatenating Arrays

# np.concatenate((array1, array2))

In [2]:
# Example 5.1

import numpy as np

a1 = np.array([0, 1, 2])
a2 = np.array([3, 4, 5])

myArr = np.concatenate((a1, a2))

print(myArr)

[0 1 2 3 4 5]


In [3]:
# Axis, a Big Issue

# axis = 0 # join two arrays vertically
# axis = 1 # join two arrays horizontally

In [4]:
# Example 5.2
# Assume that there are two 2-d arrays that will be concatenated:

# Array1 Array2
# [1, 2][5, 6]
# [3, 4][7, 8]

In [5]:
# Concatenate Arrays (axis=0)

# np.concatenate((array1, array2), axis=0)

In [6]:
# Example 5.3

import numpy as np

a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])

myArr = np.concatenate((a1, a2), axis=0)

print(myArr)

[[11 12 13]
 [14 15 16]
 [21 22 23]
 [24 25 26]]


In [7]:
# Concatenate Arrays (axis=1)

# np.concatenate((array1, array2), axis=1)

In [8]:
# Example 5.4

import numpy as np

a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])

myArr = np.concatenate((a1, a2), axis=1)

print(myArr)

[[11 12 13 21 22 23]
 [14 15 16 24 25 26]]


In [9]:
# Stack Arrays (axis=0)

# np.stack((array1, array2), axis=0)

In [10]:
# Example 5.5

import numpy as np

a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])

myArr = np.stack((a1, a2), axis=0)

print(myArr)

[[[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]


In [11]:
# Stack Arrays (axis=1)

# np.stack((array1, array2), axis=1)

In [12]:
# Example 5.6

import numpy as np

a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])

myArr = np.stack((a1, a2), axis=1)

print(myArr)

[[[11 12 13]
  [21 22 23]]

 [[14 15 16]
  [24 25 26]]]


In [13]:
# Join Arrays Vertically

# np.vstack((array1, array2))

In [14]:
# Example 5.7

import numpy as np

a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])

myArr = np.vstack((a1, a2))

print(myArr)

[[11 12 13]
 [14 15 16]
 [21 22 23]
 [24 25 26]]


In [15]:
# Join Arrays Horizontally

# np.hstack((array1, array2))

In [16]:
# Example 5.8

import numpy as np

a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])

myArr = np.hstack((a1, a2))

print(myArr)

[[11 12 13 21 22 23]
 [14 15 16 24 25 26]]


In [17]:
# Join 1d Arrays to be 3d Array

# np.dstack((array1,array2))

In [18]:
# Example 5.9

import numpy as np

a1 = np.array([11,12,13]) # 1d array
a2 = np.array([14,15,16]) # 1d array

myArr = np.dstack((a1,a2))

print(myArr)

[[[11 14]
  [12 15]
  [13 16]]]


In [19]:
# Join 2d Arrays to be 3d Array

# np.dstack((array1,array2))

In [20]:
# Example 5.10

import numpy as np

a1 = np.array([[11],[12],[13]]) # 2d array
a2 = np.array([[14],[15],[16]]) # 2d array

myArr = np.dstack((a1,a2))

print(myArr)

[[[11 14]]

 [[12 15]]

 [[13 16]]]


In [21]:
# Sorting Number Array

# np.sort(array)

In [22]:
# Example 5.11

import numpy as np

myArr = np.array([[ 2, 0, 3, 1 ], [ 7, 5, 6, 4 ]])

print(np.sort(myArr))

[[0 1 2 3]
 [4 5 6 7]]


In [23]:
# Sort String Array

# np.sort(array)

In [24]:
# Example 5.12

import numpy as np

myArr = np.array(['dove', 'buffalo', 'antilope','camel'])

print(np.sort(myArr))

['antilope' 'buffalo' 'camel' 'dove']


In [25]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.