In [1]:
# Split an Array

# array_split( array, number )

In [2]:
# Example 6.1

import numpy as np

myArr = np.array([10, 20, 30, 40, 50, 60])
arr = np.array_split(myArr, 3)

print(arr)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [3]:
# Split Less Elements

In [4]:
# Example 6.2

import numpy as np

myArr = np.array([10, 20, 30, 40, 50, 60])
arr = np.array_split(myArr, 4)

print(arr)

[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [5]:
# Access Split Array

# arr[index] # arr is an array that has been split

In [6]:
# Example 6.3

import numpy as np

myArr = np.array([10, 20, 30, 40, 50, 60])
arr = np.array_split(myArr, 3)

print(arr)
print(arr[0])
print(arr[1])
print(arr[2])

[array([10, 20]), array([30, 40]), array([50, 60])]
[10 20]
[30 40]
[50 60]


In [7]:
# Split 2-D Arrays

# array_split( array, number )

In [8]:
# Example 6.4

import numpy as np

myArr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) # 2d array
arr = np.array_split(myArr, 2)

print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [9]:
# Split Vertically

# vsplit(array, number)

In [10]:
# Example 6.5

import numpy as np

myArr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) # 2d array
arr = np.vsplit(myArr, 2)

print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [11]:
# Split Horizontally

# hsplit(array, number)

In [12]:
# Example 6.6

import numpy as np

myArr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) # 2d array
arr = np.hsplit(myArr, 2)

print(arr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [13]:
# Find Array Index

# where(array == value)

In [14]:
# Example 6.7

import numpy as np

myArr = np.array([0, 3, 2, 3, 4, 5, 3])
arr = np.where(myArr == 3)

print(arr)

(array([1, 3, 6], dtype=int64),)


In [15]:
# Where is Even/Odd Number?

In [16]:
# Example 6.8

import numpy as np

myArr = np.array([ 10, 55, 21, 62, 29, 75, 36, 98])

even = np.where(myArr%2==0)
print(even)

odd = np.where(myArr%2==1)
print(odd)

(array([0, 3, 6, 7], dtype=int64),)
(array([1, 2, 4, 5], dtype=int64),)


In [17]:
# Search Index in a Location

# searchsorted( array, value )

In [18]:
# Example 6.9

import numpy as np

myArr = np.array([24, 35, 46, 57, 68])
arr1 = np.searchsorted(myArr, 45)
arr2 = np.searchsorted(myArr, 47)

print(arr1)
print(arr2)

2
3


In [19]:
# Search More Indexes

# searchsorted( array, [v1, v2, v3,…] )

In [20]:
# Example 6.10

import numpy as np

myArr = np.array([13, 24, 35, 46, 57, 68, 79])
arr = np.searchsorted(myArr, [15, 45, 65])

print(arr)

[1 3 5]


In [21]:
# Filter Array by Boolean

In [22]:
# Example 6.11

import numpy as np

myArr = np.array([0, 1, 2, 3, 4, 5])
arr = myArr[[True, False, True, False, False, True]]

print(arr)

[0 2 5]


In [23]:
# Filter Array by Condition

In [24]:
# Example 6.12

import numpy as np

myArr = np.array([0, 1, 2, 3, 4, 5])

filter = myArr >= 3 # return true if meet the condition
arr = myArr[filter]

print(filter)
print(arr)

[False False False  True  True  True]
[3 4 5]


In [25]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.