In [1]:
# NumPy ufuncs

In [2]:
# Example 7.1

import numpy as np

list1 = [10, 20, 30, 40]
list2 = [80, 70, 60, 50]
list3 = np.add(list1, list2)

print(list3)

[90 90 90 90]


In [3]:
# Check NumPy ufunc

# type(np.function_name)

In [4]:
# Example 7.2

import numpy as np

print(type(np.add))
print(type(np.subtract))
print(type(np.multiply))
print(type(np.divide))

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


In [5]:
# Create My Own ufunc

# frompyfunc(myFunction, number1, number2)

In [6]:
# Example 7.3

import numpy as np

def myMultiply(a, b): # define my own function
    return a*b

myMultiply = np.frompyfunc(myMultiply, 2, 1)

print(myMultiply([0, 1, 2, 3, 4 ], [5, 6, 7, 8, 9]))

[0 6 14 24 36]


In [7]:
# Arithmetic ufunc

In [8]:
# Example 7.4
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([1, 2, 3])

a = np.add(arr1, arr2)
s = np.subtract(arr1, arr2)
m = np.multiply(arr1, arr2)
d = np.divide(arr1, arr2)

print(a)
print(s)
print(m)
print(d)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [9]:
# power(), mod(), remainder()

In [10]:
# Example 7.5

import numpy as np

arr1 = np.array([10,10,10])
arr2 = np.array([2, 3, 4])

p = np.power(arr1, arr2)
m = np.mod(arr1, arr2)
r = np.remainder(arr1, arr2)

print(p)
print(m)
print(r)

[  100  1000 10000]
[0 1 2]
[0 1 2]


In [11]:
# trunc() & fix()

# trunk([ floating_numbers ])
# fix([ floating_numbers ])

In [12]:
# Example 7.6

import numpy as np

t = np.trunc([-2.71828, 2.71828])
f = np.fix([-2.71828, 2.71828])

print(t)
print(f)

[-2.  2.]
[-2.  2.]


In [13]:
# around(), ceil(), floor()

# around() returns a value being rounded off.
# ceil() returns a least integer greater than itself.
# floor() returns a largest integer less than itself.

In [14]:
# Example 7.7

import numpy as np

a = np.around(7.555, 2) # “2” means two decimal places
c = np.ceil(7.555)
f = np.floor(7.555)

print(a)
print(c)
print(f)

7.56
8.0
7.0


In [15]:
# log2(), log10(), log()

# log2(array) # perform log in base 2
# log10(array) # perform log in base 10
# log(array) # perform log in base e

In [16]:
# Example 7.8

import numpy as np

arr = np.arange(1,4) # the range is from 1 to 3

print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr))

[0.        1.        1.5849625]
[0.         0.30103    0.47712125]
[0.         0.69314718 1.09861229]


In [17]:
# Log in Any Base

# from math import log

# math.log(number, base)

In [18]:
# Example 7.9

from math import log

import numpy as np

print( log(16, 4) ) # the base is 4

2.0


In [19]:
# Sum of Arrays

# sum( [array1, array2, array3] )

In [20]:
# Example 7.10

import numpy as np

a1 = np.array([10, 20, 30])
a2 = np.array([10, 20, 30])
a3 = np.array([10, 20, 30])

myArr = np.sum([a1, a2, a3])

print(myArr)

180


In [21]:
# Sum & Axis=0

In [22]:
# Example 7.11

import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

myArr = np.sum([a1, a2], axis=0)

print(myArr)

[5 7 9]


In [23]:
# Sum & Axis=1

In [24]:
# Example 7.12

import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

myArr = np.sum([a1, a2], axis=1)

print(myArr)

[ 6 15]


In [25]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.