In [1]:
# Cumulative Sum

# cumsum(array)

In [2]:
# Example 8.1

import numpy as np

myArr = np.array([10, 20, 30, 40])
arr = np.cumsum(myArr)

print(arr)

[ 10  30  60 100]


In [3]:
# Difference of Array

# diff(myArr)

In [4]:
# Example 8.2

import numpy as np

myArr = np.array([2, 5, 6, 8])
arr = np.diff(myArr)

print(arr)

[3 1 2]


In [5]:
# Once More Difference

# diff(myArr, n = number)

In [6]:
# Example 8.3

import numpy as np

myArr = np.array([2, 5, 6, 8])
arr = np.diff(myArr, n=2)

print(arr)

[-2  1]


In [7]:
# Product of an Array

# prod(array)

In [8]:
# Example 8.4

import numpy as np

myArr = np.array([10, 20, 30, 40])

num = np.prod(myArr) # 10*20*30*40

print(num)

240000


In [9]:
# Product of Arrays

# product = product1 * product2 * product3……

In [10]:
# Example 8.5

import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

num = np.prod([a1, a2]) # 1*2*3*4*5*6

print(num)

720


In [11]:
# Product & Axis=0

In [12]:
# Example 8.6

import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

myArr = np.prod([a1, a2], axis=0)

print(myArr)

[ 4 10 18]


In [13]:
# Product & Axis=1

In [14]:
# Example 8.7

import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

myArr = np.prod([a1, a2], axis=1)

print(myArr)

[  6 120]


In [15]:
# Cumulative Product

# cumprod(array)

In [16]:
# Example 8.8

import numpy as np

myArr = np.array([1, 2, 3, 4])
arr = np.cumprod(myArr)

print(arr)

[ 1  2  6 24]


In [17]:
# Quotient of Array

# divmod( array, divisor)

In [18]:
# Example 8.9

import numpy as np

arr = np.arange(2,7) # create an arr[ 2,3,4,5,6 ]

print(divmod(arr, 2))

(array([1, 1, 2, 2, 3], dtype=int32), array([0, 1, 0, 1, 0], dtype=int32))


In [19]:
# Lowest Common Multiple

# lcm.reduce(array)

In [20]:
# Example 8.10

import numpy as np

myArr = np.array([2, 5, 8])
num = np.lcm.reduce(myArr)

print(num)

40


In [21]:
# Greatest Common Divisor

# gcd.reduce(array)

In [22]:
# Example 8.11

import numpy as np

myArr = np.array([12, 6, 21, 9, 24])
num = np.gcd.reduce(myArr)

print(num)

3


In [23]:
# Rearrange the Array

# random.permutation(array)
# random.shuffle(array)

In [24]:
# Example 8.12

from numpy import random
import numpy as np

myArr = np.array([1, 2, 3, 4, 5])
arr = random.permutation(myArr)

print(arr)

random.shuffle(myArr)

print(myArr)

[3 2 5 4 1]
[5 4 2 1 3]


In [25]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.